config/routes.rb
Rails.application.routes.draw do
  root to: 'assignments#index'

  get '/auth/github/callback', to: "application#authenticate"
  get '/logout', to: "application#logout"
  get '/outcomes', to: "assignments#outcomes"
  get '/students/:github_id/summary', to: "submissions#summary"
  resources :students, only: [:index, :show]
  get 'students/:github_id/submissions', to: "submissions#index"

  resources :assignments do
    resources :submissions
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :submissions, dependent: :destroy
  after_create :seed_submissions

  def issues_for(submission, token)
    issues(token).select{ |issue| issue.user_id == submission.github_id }
  end

  def issues(token, url=nil, isshs=[])
    @issues ||= begin
      if self.repo_url
        url ||= "https://api.github.com/repos/" + self.repo_url.gsub(/https:\/\/github\.com\//,"") + "/issues?state=all&access_token="+token
        res = HTTParty.get(url)
        isshs << JSON.parse(res.body)
        isshs.flatten!(1)
        if res.headers["link"]
          next_url = res.headers["link"].match(/<(.*)>; rel="next"/)
          if next_url[1]
            self.issues(token, next_url[1], isshs)
          end
        end

        @issues = isshs.map{|i| Issue.new(i)}
      else
        @issues = {}
      end
    rescue Exception => e
      logger.warn(e)
      @issues = {}
    end
    @issues
  end

  def completion_count
    self.submissions.where(status: "complete").size
  end

  def completion_rate
    (100 * (self.completion_count.to_f / self.submissions.size)).round(0)
  end

  def summary_info
    summary_items = [assignment_type]
    summary_items << weekday if weekday?
    summary_items << "due: #{due_date}" if due_date?
    summary_items
  end

    def to_s
    "#{title} (#{assignment_type})"
  end

  private
  def seed_submissions
    Student.all.each do |student|
      if student.name
        self.submissions.create( github_id: student.github_user_id )
      end
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  skip_before_filter :authorize_user!, only: [:index]
  before_filter :authorize_instructor!, except: [:index]

  def index
    @assignment = Assignment.new
    @assignments = Assignment.order(created_at: :desc)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: Assignment.order(due_date: :desc) }
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
    if params[:squad]
      @submissions = @assignment.submissions.select do |s|
        s.student.squad.downcase == params[:squad].downcase
      end
    else
      @submissions = @assignment.submissions
    end
    @submissions = @submissions.sort_by do |s|
      [s.student.squad, s.student.last_name]
    end
    @students = Student.all
    @squads = ["Ada","Bash","C","Dart","Elixir","Fortran"]
    respond_to do |format|
      format.html
      format.json { render json: @assignment}
    end
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.json { render json: @assignment}
      end
    end
  end

  def edit
    @assignment = Assignment.find_by(weekday: params[:id]) || Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find_by(weekday: params[:id]) || Assignment.find(params[:id])
    if @assignment.update(assignment_params)
      respond_to do |format|
        format.html {redirect_to assignment_path(@assignment)}
        format.json { render json: @assignment}
      end
    end
  end

  def destroy
    @assignment = Assignment.find_by(weekday: params[:id]) ||  Assignment.find(params[:id])
    if @assignment.destroy
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.json { render json: @assignment}
      end
    end
  end

  def outcomes
    @assignments = Assignment.where(assignment_type: "outcomes")
  end

  private
  def assignment_params
    params.require(:assignment).permit(:title, :weekday, :due_date, :repo_url, :rubric_url, :assignment_type)
  end
end

app/views/assignments/_submission.html.erb
<% issue = @issues[submission.student["github_user_id"]] %>
<tr>
  <th><%= link_to submission.student["name"], edit_assignment_submission_path(@assignment, submission)  %></th>
  <% if is_an_instructor? %>
    <td>
      <%= link_to("Tracker", student_url(submission.student),  title: "To Student Tracker", target: '_blank') %>
    </td>
  <% end %>
  <% if issue %>
    <% issue_label = (issue[:state] == "open" ? "issue*" : "issue") %>
    <td class=<%= issue[:state] %>><%= link_to issue_label, issue[:url]%></td>
    <td><%= markdown(issue[:comments])%></td>
  <% else %>
    <% if submission.assignment.assignment_type == "homework" %>
      <td class="missing">no issue!</td>
    <% elsif !submission.repo_url.blank? %>
      <td><%= link_to "View on GitHub", submission.repo_url %></td>
    <% else %>
      <td></td>
    <% end %>
    <td></td>
  <% end %>
  <td class="status">
    <% if submission.assignment.assignment_type == "homework" %>
      <%= check_box_tag submission.id, true, submission.status === "complete", :"data-submit" => assignment_submissions_path(@assignment) + "/#{submission.id}" %>
      <label for="<%= submission.id %>">Complete</label>
    <% elsif submission.assignment.assignment_type == "project" %>
      <% if submission.status && !submission.status.blank? %>
        Complete
      <% end %>
    <% end %>
  </td>
</tr>

app/views/assignments/_submission_form.html.erb
<%= form_for([@assignment, @assignment.submissions.build]) do |f| %>
  <p>
    <%= f.label :github_id %><br>
    <%= f.text_field :github_id %>
  </p>
  <p>
    <%= f.label :html_url %><br>
    <%= f.text_area :html_url %>
  </p>
  <p>
    <%= f.label :repo_url %><br>
    <%= f.text_area :repo_url %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/assignments/_table_header.html.erb
<%= form_for @assignment do |f| %>
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.select :assignment_type, [["homework","homework"],["outcomes","outcomes"],["project","project"]] %>
    <%= f.text_field :repo_url, placeholder: "Repo Url"%>
    <%= f.date_field :due_date %>
    <%= f.submit %>
<% end %>
  <tr>
    <th>Title</th>
    <th>Percent Complete</th>
    <th>Type</th>
    <th>Repo Url</th>
    <th>Due Date</th>
  </tr>

app/views/assignments/edit.html.erb
<h1><%= title "Editing #{@assignment}" %></h1>

<table>
  <thead>
    <%= render 'table_header' %>
  <thead>
</table>

app/views/assignments/index.html.erb
<% if session[:token] %>

  <h1>Assignments</h1>
  <table class="tablesorter">
    <thead>
      <%= render 'table_header' %>
    </thead>
    <tbody>
      <% @assignments.each do |assignment| %>
        <tr>
          <td><%= link_to "#{assignment.title}", assignment_path(assignment) %></td>
          <td><%= "%#{assignment.completion_rate}" %></td>
          <td><%= assignment.assignment_type %></td>
          <td><%= link_to repo_name(assignment.repo_url), assignment.repo_url %></td>
          <td><%= assignment.due_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/assignments/outcomes.html.erb
<h1><%= title "Outcomes related Assignments" %></h1>

<% @assignments.each do |assignment| %>
<div class='assignment'>
  <h3><%= link_to assignment.title, assignment_path(assignment) %></h3><small>(<%= assignment.assignment_type %>)</small>
  <small>Updated <%= time_ago_in_words(assignment.updated_at) %> ago</small>
</div>
<% end %>

app/views/assignments/show.html.erb
<% meta title: @assignment %>
<h1>
  <%= link_to_if @assignment.repo_url.present?, @assignment.title, @assignment.repo_url %>
  <span>(<%= "#{@assignment.summary_info.join(", ")})" %></span>
</h1>

<% if session[:token] %>
  <%= link_to "edit", edit_assignment_path(@assignment)%>
  <%= link_to 'delete', assignment_path(@assignment), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<div class='sort-by'>
<% @squads.each do |squad| %>
  <%= link_to squad, assignment_path(@assignment) + "?squad=#{squad.downcase}" %>
<% end %>
</div>
<h2>Submissions</h2>

<table>
  <%= render partial: @submissions, locals: {header: :student_name} %>
</table>