config/routes.rb
Rails.application.routes.draw do
  root to: 'assignments#index'

  get '/auth/github/callback', to: "application#authenticate"
  get '/logout', to: "application#logout"
  get '/outcomes', to: "assignments#outcomes"
  get '/students/:github_id/summary', to: "submissions#summary"
  resources :students, only: [:index, :show]
  get 'students/:github_id/submissions', to: "submissions#index"

  resources :assignments do
    resources :submissions
  end

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :assignment

  def students
    Student.all
  end

  def issues(token)
    self.assignment.issues_for(self, token)
  end

  def student
    return Student.find(self.github_id)
  end

  def as_json(options={})
    super.as_json(options).merge({
      assignment_title: assignment_title,
      assignment_type: assignment_type,
      assignment_repo_url: assignment_repo_url,
      assignment_due_date: assignment_due_date,
      student_name: student.name
    })
  end

  def assignment_title
    self.assignment && self.assignment.title
  end

  def assignment_repo_url
    self.assignment && self.assignment.repo_url
  end

  def assignment_due_date
    self.assignment && self.assignment.due_date
  end

  def assignment_type
    self.assignment && self.assignment.assignment_type
  end

  def involves_squad
    studs = students.select{|each_student|
      each_student.squad === self.student.squad
    }
    query = []
    studs.each{|student|
      query.push("involves%3A#{student.github_username}")
    }
    return query.join("+")
  end

  def to_s
    items_to_display = []
    items_to_display << "#{student.name}'s" if student
    items_to_display <<  %Q("#{self.assignment}")
    items_to_display.join(" ")
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :authorize_instructor!, except: [:index]

  def index
    if params[:github_id]
      @submissions = Submission.where(github_id: params[:github_id], private: [nil,false])
    else
      @students = Student.all
      @assignment = Assignment.find(params[:assignment_id])
      @submissions = @assignment.submissions
    end

    respond_to do |format|
      format.html
      format.json { render status: 200, json: @submissions.to_json }
    end
  end

  def summary
    @submissions = Submission.where(github_id: params[:github_id], private: [nil,false])
    summary = {complete: 0, incomplete: 0, total: @submissions.length}
    @submissions.each do |submission|
      unless submission.status.blank?
        summary[:complete] += 1
      end

    end
    summary[:percent_complete] = ((summary[:complete].to_f / summary[:total].to_f) * 100.0).round(0)
    render json: summary
  end

  def new
    @assignment = Assignment.find_by(weekday: params[:assignment_id]) || Assignment.find(params[:assignment_id])
    @students = Student.all
    @submissions = @assignment.submissions
    @submission = @assignment.submissions.build
    respond_to do |format|
      format.html
      format.json { render status: 200, json: @submissions.to_json }
    end

  end

  def show
    @assignment = Assignment.find_by(weekday: params[:assignment_id]) || Assignment.find(params[:assignment_id])
    @submissions = @assignment.submissions
    @submission = Submission.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render status: 200, json: @submission.to_json }
    end
  end

  def create
    @assignment = Assignment.find(params[:assignment_id])
    @submission  = @assignment.submissions.new(submission_params)
    if @submission.save
      respond_to do |format|
        format.html {redirect_to assignment_submissions_path(@assignment) }
        format.json {render json: @assignment}
      end
    end
  end

  def edit
    @assignment = Assignment.find_by(weekday: params[:assignment_id]) || Assignment.find(params[:assignment_id])
    @submission = Submission.find(params[:id])
    @students = Student.all
  end

  def update
    @submission = Submission.find(params[:id])
    if @submission.update(submission_params)
      respond_to do |format|
        format.html {redirect_to edit_assignment_submission_path(@submission.assignment,@submission)}
        format.json {render json: @submission}
      end
    end
  end

  def destroy
    @assignment = Assignment.find_by(weekday: params[:assignment_id]) || Assignment.find(params[:assignment_id])
    @submission = Submission.find(params[:id])
    if @submission.destroy
      respond_to do |format|
        format.html {redirect_to assignment_path(@assignment) }
        format.json {render json: @submission}
      end
    end
  end

  private
  def submission_params
    params.require(:submission).permit(:github_id, :html_url, :repo_url, :status, :private)
  end
end

app/views/submissions/_form.html.erb
<div autosave>
  <br>
  <small>Updated <span class='js-updated-at js-time-ago'><%= @submission.updated_at %></span></small>
  <%= form_for([@assignment, @submission]) do |f|%>
    <h2>
      <%= @submission.student.name %>
    </h2>
    <p>
      <%= f.check_box :private, style: "display:none;"%>
      <%= f.label :private %>
    </p>
    <p>
      <%= f.text_field :html_url, placeholder: "HTML URL" %>
      <%= f.text_field :repo_url, placeholder: "Repo URL"%>
    </p>
    <p>
      <%= f.label :status %><br>
      <%= f.text_area :status %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/submissions/_submission.html.erb
<% issues = submission.issues(session[:token]) %>
<% assignment = submission.assignment %>
<tr>
  <th>
    <% if header == :student_name %>
      <%= link_to submission.student.name, student_path(submission.student.github_user_id) %><br />
    <% elsif header == :assignment_name %>
      <%= link_to submission.assignment.title, submission.assignment %><br />
    <% else %>
      <% fail "Unsupported header (#{header}).  Did you mean :student_name or :assignment_name?" %>
    <% end %>

    (<a href="<%= "#{assignment.repo_url}/issues?q=#{submission.involves_squad}" %>" target="_blank"><%= submission.student.squad %></a>)<br />
    <%= link_to "Edit", edit_assignment_submission_path(assignment, submission) %>
  </th>

  <td>
    <% if issues.empty? && assignment.assignment_type == "homework" %>
      <span class="x"></span>
    <% else %>
      <% issues.each do |issue| %>
        <%= render partial: "issues/issue", object: issue  %>
      <% end %>
    <% end %>
  </td>

  <td class="status">
    <% if assignment.assignment_type == "homework" %>
      <%= check_box_tag submission.id, true, submission.status === "complete", :"data-submit" => assignment_submissions_path(assignment) + "/#{submission.id}" %>
      <label for="<%= submission.id %>">Complete</label>
    <% else %>
      <%= submission.status %>
    <% end %>
  </td>
</tr>

app/views/submissions/edit.html.erb
<h1><%= title "Editing #{@submission}" %></h1>
<%= link_to "Preview", assignment_submission_path(@assignment, @submission) %>
<%= render 'form' %>

app/views/submissions/index.html.erb
<table>
  <%= render partial: @submissions, locals: {header: :student_name} %>
</table>
<h1><%= title "Submissions for #{@assignment}" %></h1>

app/views/submissions/new.html.erb
<br><%= link_to "&larr; Back".html_safe, "../" %>
<h1><%= title "New submission for #{@assignment.title}" %></h1>
<%= render "form" %>

app/views/submissions/show.html.erb
<h1><%= title "#{@submission}" %></h1>

<table>
  <%= render partial: @submission, locals: {header: :assignment_name} %>
</table>