config/routes.rb
Rails.application.routes.draw do
  root to: 'assignments#index'

  get '/auth/github/callback', to: "application#authenticate"
  get '/logout', to: "application#logout"
  get '/outcomes', to: "assignments#outcomes"
  get '/students/:github_id/summary', to: "submissions#summary"
  resources :students, only: [:index, :show]
  get 'students/:github_id/submissions', to: "submissions#index"

  resources :assignments do
    resources :submissions
  end

end

app/views/layouts/_github_ribbon.html.erb
<!-- Copied from : https://github.com/blog/273-github-ribbons -->
<a href="https://github.com/wdidc/assignments">
  <img style="position: absolute; top: 0; right: 0; border: 0;"
        src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67"
        alt="Fork me on GitHub"
        data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png">
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic title: 'Assignments' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.22.3/js/jquery.tablesorter.js" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
</head>
<body>
  <header class='cf'>
    <nav>
      <ul>
        <li class="home">
          <a href="/"><i class="icon icon-home"></i></a>
        </li>
        <li>
          <%= link_to "Students", students_path %>
        </li>

        <li class='login'>
          <% if session[:token] %>
            <%= link_to "Log out", '/logout' %>
          <% else %>
            <%= link_to "Log in with GitHub", '/auth/github' %>
          <% end %>
        </li>
      </ul>
      <%= render 'layouts/github_ribbon' %>
    </nav>

  </header>
  <%= yield %>

</body>
</html>